### ISSUE TITLE
Plex server connect failure && cannot manually set the status of a request.

### ISSUE THREAD

**Issue by bendini20** [petio-team/petio#524] opened 2021-08-02 22:11 UTC
**Describe the bug**
Petio can no longer connect to my Plex server, therefore it cannot tell when a request has been fulfilled or not. I try to re-login with Plex, and it will say config loaded...and then say test failed. Furthermore, I was willing to manually set the status of requests until the bugs were fixed, however when I try to do so, I cannot click save as the button is greyed out.

**To Reproduce**
1. General
2. Plex
3. Login with Plex
4. Test
5. See error / failure

**Expected behavior**
Test works and Petio can communicate with Plex, as well as being able to manually set request status.

**Screenshots**
![image](https://user-images.githubusercontent.com/47575219/127929663-1d0fd3a3-25c3-4946-ab35-eb9b7c9c6800.png)
![image](https://user-images.githubusercontent.com/47575219/127929683-378294bb-2ee7-4f38-ab94-83b4e53c0f79.png)
![image](https://user-images.githubusercontent.com/47575219/127929916-d55f45c2-3891-4ce5-9394-b262f9beb3b8.png)

**Desktop (please complete the following information):**
 -Running on Docker in Unraid, Version 0.5.2-alpha

**Additional context**
Looking at the logs, Petio is trying to contact Plex at the wrong docker IP since they are dynamic. There is no way to manually set Plex's IP in the Petio docker settings that I can see. Furthermore, this should not matter as the login token with Plex should be able to determine where the server is running at (IP-wise) and should be able to point Petio to the right docker IP.
![image](https://user-images.githubusercontent.com/47575219/127930233-3e1db040-2ddf-4828-9e09-5cb6eb871541.png)

**Comment by bendini20** [comment] 2021-08-03 00:18
Update: The connection to Plex issue was resolving only by fully removing Mongo and Petio dockers and reinstalling them. I suppose when I setup Petio the first time, I selected the temporary Docker IP instead of the docker network hostname, meaning it is dynamic. The issue regarding manual request status setting still needs to be addressed though.

**Comment by tatzu** [comment] 2021-12-31 15:28
just if someone else having problem with needing to change the plex server adress.
I found that you can edit the config.json file and there change the adress of the plex server.

**Comment by AshDyson** [comment] 2022-01-06 14:37
> just if someone else having problem with needing to change the plex server adress. I found that you can edit the config.json file and there change the adress of the plex server.

To add to this a Petio restart is required for it to take affect. As this was an issue relative to Plex / Petio connection and not a bug in Petio I will close this issue.

**Closed by AshDyson** 2022-01-06 14:37 UTC
Labels: bug
