### ISSUE TITLE
Path to no-poster.jpg and user-profile thumb image 404's when using base path

### ISSUE THREAD

**Issue by gilbN** [petio-team/petio#269] opened 2021-03-20 10:59 UTC
**Describe the bug**
Path to `no-poster.jpg`, `no-poster-person.jpg`and user-profile thumb image 404's when using base path

*To Reproduce**
1. add a base path

**Expected behavior**
no 404 :P

**Screenshots**

![](https://selfhosted.app/f3c10/bUXASEka63.png/raw)

**Desktop (please complete the following information):**
 - OS: docker
 - Browser chrome

**Comment by angrycuban13** [comment] 2021-03-20 18:09
@AshDyson is this a duplicate of #243 or this is different?

**Comment by gilbN** [comment] 2021-03-20 19:07
Lol I even looked for a similar issue..🤦‍♂️

**Comment by AshDyson** [comment] 2021-03-20 19:52
It's the same cause but different bug. Worth having both open

**Comment by angrycuban13** [comment] 2021-03-21 02:26
> Lol I even looked for a similar issue..🤦‍♂️ I did make it at 4AM though...

I was just making sure. You know I love you 😘

**Comment by AshDyson** [comment] 2021-03-22 20:51
Fix coming in next patch, fix referenced in #243

**Closed by AshDyson** 2021-03-22 20:51 UTC
Labels: bug
