### ISSUE TITLE
After deleting media from Radarr/Sonarr, Pelio still thinks the media is available in Plex

### ISSUE THREAD

**Issue by mkanet** [petio-team/petio#455] opened 2021-06-08 05:54 UTC
**Describe the bug**
After deleting media from Radarr/Sonarr, Pelio still thinks the media is there

Version:  **0.5.1 Alpha**
OS:            **Windows 10** 

**To Reproduce**
1. Make a request to download a movie or TV show
2. Wait for media to show up in Plex/Petio after it's downloaded successfully
3. Delete media in Radarr/Sonarr (completely removing items)
4. Pelio still shows these items are available in plex

**Expected behavior**
I expect the media to not show in Pelio after media has been deleted (and not showing in Plex anymore)

**Screenshots**
Possible related errors in console:
![Untitled picture](https://user-images.githubusercontent.com/811008/121130319-193f1400-c7e3-11eb-85d2-4c608a9e1420.png)

**PS:  Lastly, I keep getting the message below with a dark background when clicking on the TV and/or Movie section.. the spinning circle stays there a long time every time.**  

```
Building your personalised Movie Discovery…
```

**Comment by mkanet** [comment] 2021-06-08 13:25
Okay thanks.  So, how can I fix this issue?  Plex doesn't think I have this media, neither does Ombi; which is currently also connected to the same *arrs/plex.

**Comment by angrycuban13** [comment] 2021-06-08 14:55
Petio isn't Ombi, what Ombi does or how it works has no relevance to Petio. Petio connects directly to Plex and sets media availability based on what Plex reports. I'd check your Plex server to be sure the media isn't still in Plex's recycling bin or you might need to do a library refresh.

**Comment by mkanet** [comment] 2021-06-08 15:39
Hi, items are not in Plex trash; as Plex is set to "Empty trash automatically after every scan".  

I manually emptied Plex trash anyway and refreshed respective Plex libraries.  There is no trace of the medias anywhere on my server other than Petio.

Maybe there's a problem with the MongoDB database?  Maybe, Petio is having trouble communicating with Plex?  If either is true, how would I resolve this issue?

My apologies if this isn't right place for Petio support.   Maybee I should Isk for help on the DPlex iscord channel instead?

**Comment by AshDyson** [comment] 2021-06-08 17:43
So if a media item is removed from Plex it does not get retroactively removed from Petio (currently). Petio only does additive scanning at the moment meaning it will add to it's "known media" pool as things become available. I'm going to close this issue as it's a duplicate of the feature request #378 which will be applied as soon as we have the time to impliment.

**Closed by AshDyson** 2021-06-08 17:43 UTC
Labels: bug

**Comment by mkanet** [comment] 2021-06-08 18:05
@AshDyson Thank you for confirming this issue!  I'll follow https://github.com/petio-team/petio/issues/378 progress.
